//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rental")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub game_id: i32,
    pub user_id: i32,
    pub rental_date: Date,
    pub return_date: Date,
    #[sea_orm(default_value = false)]
    pub picked_up: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::board_game::Entity",
        from = "Column::GameId",
        to = "super::board_game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BoardGame,
    #[sea_orm(has_one = "super::extension_request::Entity")]
    ExtensionRequest,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::board_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoardGame.def()
    }
}

impl Related<super::extension_request::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtensionRequest.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
