//! `SeaORM` Entity, partially @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use sea_orm::prelude::async_trait::async_trait;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "rental_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub game_id: i32,
    pub user_id: i32,
    pub rental_date: Date,
    pub return_date: Date,
    pub picked_up: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::board_game::Entity",
        from = "Column::GameId",
        to = "super::board_game::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BoardGame,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::board_game::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BoardGame.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, _insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if self.rental_date.as_ref() > self.return_date.as_ref() {
            return Err(DbErr::Custom("rental_date cannot be greater than return_date".into()));
        }

        Ok(self)
    }
}
