//! `SeaORM` Entity, partially @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub surname: String,
    pub phone: String,
    pub email: String,
    pub password: String,
    #[sea_orm(default_value = 0)]
    pub penalty_points: u8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rental::Entity")]
    Rental,
    #[sea_orm(has_many = "super::rental_history::Entity")]
    RentalHistory,
}

impl Related<super::rental::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rental.def()
    }
}

impl Related<super::rental_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RentalHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
